[project]
name = "chatbot-medico-vih"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastembed>=0.8.0",
    "langchain-community<0.4",
    "langgraph>=1.2.5",
    "langgraph-cli[inmem]>=0.4.30",
    "langsmith>=0.8.16",
    "openai>=2.41.1",
    "pandas>=3.0.3",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "ragas>=0.4.3",
    "rapidfuzz>=3.14.5",
    "tiktoken>=0.13.0",
]
