"""PathRAG: relational-path retrieval with flow-based pruning (arXiv 2502.14902).

PathRAG's premise is that graph RAG's problem is REDUNDANCY, not insufficiency: LightRAG
feeds the LLM every immediate neighbour of the matched nodes, and the noise degrades the
answer. Instead it keeps only the key relational PATHS between the query-related nodes,
scored by a flow-based pruning algorithm with distance decay.

Two adaptations to this project, both driven by priority #1 (do not hallucinate):

  1. It reads the EXISTING LightRAG index (`data/lightrag_store/`) instead of building its
     own. PathRAG needs exactly what LightRAG already produced — an entity graph with
     described edges and per-node source chunks — so a second index would cost 1.5 h and
     duplicate the corpus for nothing. All the store-format knowledge lives in `_PathStore`,
     the single point coupled to lightrag-hku's on-disk layout.
  2. The paths are used TWICE, with different privileges. As a chunk SELECTOR they decide
     which literal chunks reach the prompt (those stay the only citable evidence, mapped back
     through `source_id`). As a CONCEPT MAP their textual form also reaches the generator, but
     explicitly marked non-citable — it may guide the reasoning across hops, never support a
     quote. The paper's path-based prompting, made safe for a clinical setting.

Usage:
    Smoke the store and a demo query:  .venv\\Scripts\\python.exe -m retrieval.pathrag
    (the LightRAG index must exist:    .venv\\Scripts\\python.exe -m retrieval.graph)
"""
import asyncio
import base64
import heapq
import json
import os
import sys
import threading
from dataclasses import dataclass, field
from typing import cast

import numpy as np
from pydantic import BaseModel

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from rag import REPHRASE_MODEL, _ABBREV_LIST, chat_model, client, get_embedding, rephrase

from ._common import canonical_key, expand_abbrevs, house_tail, map_chunk_ids_to_payloads

# --- Config ---------------------------------------------------------------
STORE_DIR = os.path.join(ROOT, "data", "lightrag_store")
GRAPHML = os.path.join(STORE_DIR, "graph_chunk_entity_relation.graphml")
VDB_ENTITIES = os.path.join(STORE_DIR, "vdb_entities.json")
TEXT_CHUNKS = os.path.join(STORE_DIR, "kv_store_text_chunks.json")
# Spanish descriptions for the concept map, generated by `--describe-es` (see _describe_es).
# Kept OUTSIDE the LightRAG store so regenerating them can never disturb the graph mode.
DESCRIPTIONS_ES = os.path.join(STORE_DIR, "descriptions_es.jsonl")

EMBEDDING_DIM = 3072          # text-embedding-3-large, as indexed by retrieval.graph
SEP = "<SEP>"                 # LightRAG's separator inside multi-valued source_id fields

# Paper defaults (N=40 retrieved nodes, K=15 kept paths, decay alpha=0.7).
NODE_TOP_N = 40
MAX_PATHS = 15
DECAY = 0.7
PRUNE_THRESHOLD = 0.01        # early stop: below this a node contributes nothing downstream
MAX_HOPS = 4                  # safety cap; the decay reaches the threshold at ~4 hops anyway
DESC_CHARS = 220              # per-item truncation in the concept map (keeps tokens bounded)
# The paths of a broad question touch well over a hundred chunks; keeping the most reliable
# ones bounds the rerank (its cost is linear in candidates) and matches the graph mode's
# chunk_top_k=20 budget, so both graph modes hand the reranker a comparable pool.
PRIMARY_CHUNK_CAP = 20
OPENIE_CONCURRENCY = 8        # parallel LLM calls when regenerating descriptions (build only)
# Items described per call. A chunk can hold up to 183 of them, and asked for all at once the
# model silently returns fewer (159/183 measured); the median chunk has 17, so batching at 40
# costs ~20 extra calls over the whole corpus and keeps every item described.
DESCRIBE_BATCH = 40


_KEYWORDS_SYS = f"""Eres un extractor de PALABRAS CLAVE para buscar en un grafo de conceptos construido sobre las guías clínicas de VIH (GeSIDA). NO respondes la pregunta.

Extrae de la pregunta las ENTIDADES y CONCEPTOS clínicos concretos que habrá que localizar en el grafo: fármacos, patologías, coinfecciones, situaciones del paciente (gestación, insuficiencia renal…), pruebas y parámetros. De 3 a 8 palabras clave, cada una un término corto y autocontenido (no frases largas).

NORMALIZACIÓN: para cualquier fármaco/término de la lista (sigla o nombre), escríbelo en la forma «nombre completo (SIGLA)». Solo términos de la lista; no inventes siglas.

LISTA DE ABREVIATURAS (SIGLA = nombre):
{_ABBREV_LIST}

Devuelve keywords (lista de strings en español)."""


class _Keywords(BaseModel):
    keywords: list[str]


_kw_llm = None
def _get_keywords_llm():
    global _kw_llm
    if _kw_llm is None:
        _kw_llm = chat_model(REPHRASE_MODEL, temperature=0).with_structured_output(
            _Keywords, method="json_schema", strict=True
        )
    return _kw_llm


def extract_keywords(query: str) -> list[str]:
    """Stage 1 of the paper: the LLM names what to look for in the graph. On LLM failure it
    degrades to the rephrased query as a single keyword, so retrieval never blocks."""
    try:
        k = cast(_Keywords, _get_keywords_llm().invoke(
            [("system", _KEYWORDS_SYS), ("human", query)]))
        kws = [s.strip() for s in k.keywords if s and s.strip()]
        if kws:
            return kws
    except Exception:
        pass
    return [rephrase(query)]


# ---------------------------------------------------------------------------
# STORE  (the only code that knows lightrag-hku's on-disk layout)
# ---------------------------------------------------------------------------
@dataclass
class _PathStore:
    """The LightRAG index as PathRAG needs it: a walkable graph, node embeddings to match the
    query against, and the mapping back to our citable chunks."""
    graph: "object"                       # networkx.Graph (undirected entity graph)
    node_names: list[str]                 # row i of `node_emb` describes node_names[i]
    node_emb: np.ndarray                  # (n_nodes, 3072), L2-normalized
    node_row: dict[str, int] = field(default_factory=dict)
    lr_to_chunk: dict[str, str] = field(default_factory=dict)  # LightRAG chunk id -> our chunk_id
    desc_es: dict[str, str] = field(default_factory=dict)      # item key -> Spanish description


def _decode_matrix(vdb: dict) -> np.ndarray:
    """LightRAG stores the vectors as ONE base64 float32 blob, row-aligned with `data`."""
    dim = int(vdb["embedding_dim"])
    rows = len(vdb["data"])
    raw = base64.b64decode(vdb["matrix"])
    expected = rows * dim * 4
    if len(raw) != expected:
        raise SystemExit(
            f"{VDB_ENTITIES}: unexpected matrix size ({len(raw)} bytes, expected {expected} "
            f"for {rows}x{dim} float32). The lightrag-hku store layout changed — update "
            f"_PathStore in retrieval/pathrag.py."
        )
    return np.frombuffer(raw, dtype=np.float32).reshape(rows, dim)


def _build_store() -> _PathStore:
    import networkx as nx

    for path in (GRAPHML, VDB_ENTITIES, TEXT_CHUNKS):
        if not os.path.isfile(path):
            raise SystemExit(
                f"{path} not found. PathRAG reads the LightRAG index; build it first: "
                f".venv\\Scripts\\python.exe -m retrieval.graph"
            )

    graph = nx.read_graphml(GRAPHML)

    with open(VDB_ENTITIES, encoding="utf-8") as fh:
        vdb = json.load(fh)
    if int(vdb["embedding_dim"]) != EMBEDDING_DIM:
        raise SystemExit(
            f"{VDB_ENTITIES}: embedding_dim {vdb['embedding_dim']} != {EMBEDDING_DIM}. "
            f"The index was built with a different embedding model."
        )
    emb = _decode_matrix(vdb)                       # already L2-normalized by LightRAG
    names = [d.get("entity_name", "") for d in vdb["data"]]

    # Each chunk was inserted as its own LightRAG document keyed by OUR chunk_id, so a
    # LightRAG chunk's `full_doc_id` IS our chunk_id — this is the bridge from the graph's
    # source_id back to citable payloads. (535 LightRAG chunks -> 517 of ours: a few long
    # chunks were split, several mapping to the same payload.)
    with open(TEXT_CHUNKS, encoding="utf-8") as fh:
        text_chunks = json.load(fh)
    lr_to_chunk = {lr_id: v["full_doc_id"] for lr_id, v in text_chunks.items()
                   if v.get("full_doc_id")}

    return _PathStore(graph=graph, node_names=names, node_emb=emb,
                      node_row={n: i for i, n in enumerate(names)},
                      lr_to_chunk=lr_to_chunk, desc_es=_load_descriptions_es())


_store: _PathStore | None = None
_store_lock = threading.Lock()
def _get_store() -> _PathStore:
    """Load the store once (double-checked locking: retrieval runs branches in parallel)."""
    global _store
    if _store is None:
        with _store_lock:
            if _store is None:
                _store = _build_store()
    return _store


def _chunk_ids_of(attrs: dict) -> list[str]:
    """Our chunk_ids behind a node/edge, via its LightRAG source_id field."""
    store = _get_store()
    raw = attrs.get("source_id") or ""
    return [store.lr_to_chunk[p] for p in raw.split(SEP) if p in store.lr_to_chunk]


# ---------------------------------------------------------------------------
# SPANISH DESCRIPTIONS  (python -m retrieval.pathrag --describe-es)
# ---------------------------------------------------------------------------
# LightRAG's extraction prompt is English, so it described a Spanish corpus in English: 84% of
# node and 70% of edge descriptions. That is harmless for the `graph` mode (there the
# descriptions only match embeddings and are then discarded) but not for PathRAG, whose
# concept map puts that text in front of a generator answering in Spanish about Spanish
# guidelines. Rather than re-extract the whole graph in Spanish (~1.5 h, and it would
# invalidate the graph mode's measured index), we regenerate ONLY the descriptions, reading
# the source chunk so they gain clinical content instead of being a mere translation.
_ITEM_SEP = "\x00"          # joins the two endpoints into one edge key


def _item_key(item) -> str:
    """Stable key for a node (its name) or an edge (both endpoints, order-independent)."""
    return item if isinstance(item, str) else _ITEM_SEP.join(sorted(item))


def _load_descriptions_es() -> dict[str, str]:
    """Load the generated Spanish descriptions.

    A concept usually appears in several chunks and is therefore described several times, from
    each chunk's angle. We keep ONE description per item, resolved by chunk_id order: the
    records are written as the async tasks finish (non-deterministic), so without sorting the
    same index would describe «TAF» differently on each build."""
    if not os.path.isfile(DESCRIPTIONS_ES):
        return {}
    with open(DESCRIPTIONS_ES, encoding="utf-8") as fh:
        records = [json.loads(line) for line in fh if line.strip()]
    out: dict[str, str] = {}
    for rec in sorted(records, key=lambda r: r["chunk_id"]):
        for key, text in rec.get("descriptions", {}).items():
            out.setdefault(key, text)          # first chunk wins, deterministically
    return out


# ---------------------------------------------------------------------------
# STAGE 2: node retrieval
# ---------------------------------------------------------------------------
def retrieve_nodes(keywords: list[str], top_n: int = NODE_TOP_N) -> dict[str, float]:
    """Match the keywords against the entity embeddings; return {node: relevance} for the
    top_n distinct CONCEPTS.

    Distinct concepts, not distinct nodes: the index holds up to seven spellings of «TAR», and
    without collapsing them by `canonical_key` they alone would fill a sixth of the budget,
    starving the concepts that actually discriminate the question (measured: the top-40 for an
    HBV question was mostly TAR variants). Keywords are abbreviation-expanded so «DTG» matches
    a node written «dolutegravir».

    The similarity is RETURNED, not discarded: path reliability needs it to stay anchored to
    the question (see `retrieve_paths`)."""
    store = _get_store()
    vecs = []
    for kw in keywords:
        try:
            v = np.asarray(get_embedding(expand_abbrevs(kw)), dtype=np.float32)
            vecs.append(v / (np.linalg.norm(v) or 1.0))
        except Exception:
            continue
    if not vecs:
        return {}
    # Best score across keywords per node (a node is relevant if ANY keyword matches it),
    # rather than an average that would dilute a strong single-keyword hit.
    sims = (store.node_emb @ np.vstack(vecs).T).max(axis=1)
    out, seen = {}, set()
    for i in np.argsort(-sims):
        name = store.node_names[i]
        key = canonical_key(name)
        if name in store.graph and key not in seen:
            seen.add(key)
            out[name] = float(sims[i])
            if len(out) >= top_n:
                break
    return _rescale(out)


def _rescale(scores: dict[str, float], floor: float = 0.1) -> dict[str, float]:
    """Spread the similarities over [floor, 1] by min-max over the retrieved set.

    Raw cosines from text-embedding-3-large sit in a narrow band (0.60-0.68 measured across a
    top-40), so multiplying by them barely reorders anything next to a flow value ranging
    1.00-1.70 — the correction would be nominal. Rescaling relative to the candidates actually
    retrieved gives relevance the same discriminating power as flow. The floor keeps the last
    candidate from collapsing to zero, which would erase every path touching it."""
    if not scores:
        return {}
    lo, hi = min(scores.values()), max(scores.values())
    if hi - lo < 1e-9:
        return {k: 1.0 for k in scores}
    return {k: floor + (1 - floor) * (v - lo) / (hi - lo) for k, v in scores.items()}


# ---------------------------------------------------------------------------
# STAGE 3: path retrieval (flow-based pruning with distance awareness)
# ---------------------------------------------------------------------------
@dataclass
class _Path:
    nodes: list[str]
    flow: float          # S(P) from the paper: how strongly the endpoints are connected
    relevance: float     # how close the path's endpoints are to the question (cosine)

    @property
    def score(self) -> float:
        """Final ranking score. See `retrieve_paths` for why flow alone is not enough."""
        return self.flow * self.relevance


def _flow_paths(start: str, targets: set[str], decay: float, threshold: float,
                max_hops: int) -> list[_Path]:
    """Propagate one unit of resource from `start` and collect the paths that reach another
    retrieved node (eq. 2-4 of the paper).

    Resource flowing into a node is its predecessor's resource, decayed by `decay` and split
    across that predecessor's neighbours — so distant and highly-connected (i.e. generic)
    nodes contribute little, which is exactly the redundancy PathRAG set out to prune. A
    branch dies as soon as its resource falls below `threshold`. The flow value is the sum of
    the resources along the path, normalized by the number of edges (eq. 4)."""
    graph = _get_store().graph
    paths: list[_Path] = []
    # Each stack item is a partial path: (nodes so far, resource at the tip, resource sum).
    stack = [([start], 1.0, 1.0)]
    while stack:
        nodes, resource, total = stack.pop()
        if len(nodes) - 1 >= max_hops:
            continue
        tip = nodes[-1]
        degree = graph.degree(tip) or 1
        flow = decay * resource / degree
        if flow < threshold:                    # early stopping (eq. 3)
            continue
        # Deterministic order: strongest edge first, ties broken by node id.
        neighbours = sorted(
            graph[tip].items(),
            key=lambda kv: (-float(kv[1].get("weight", 1.0) or 1.0), kv[0]),
        )
        for nxt, _attrs in neighbours:
            if nxt in nodes:                    # simple paths only
                continue
            extended = nodes + [nxt]
            acc = total + flow
            if nxt in targets:
                paths.append(_Path(nodes=extended, flow=acc / (len(extended) - 1),
                                   relevance=1.0))   # set by retrieve_paths
            stack.append((extended, flow, acc))
    return paths


def retrieve_paths(nodes: dict[str, float], max_paths: int = MAX_PATHS, decay: float = DECAY,
                   threshold: float = PRUNE_THRESHOLD, max_hops: int = MAX_HOPS) -> list[_Path]:
    """Key relational paths among the retrieved nodes, best first. Only the best path per node
    PAIR enters the pool (the paper's per-pair selection), so one densely connected pair cannot
    crowd out the rest of the query's structure.

    Paths are ranked by flow × relevance, NOT by flow alone. The paper ranks on flow because it
    assumes every retrieved node is relevant, leaving flow to discriminate how strongly two of
    them connect. That assumption breaks on this graph: since flow is split across a node's
    neighbours, a path between two LEAF nodes keeps almost all of it (degree 1 -> 1.70) while a
    path between the concepts that actually matter is penalized for being well connected (VHB,
    degree 23 -> 1.03; TAR, degree 210 -> 1.00). Ranking on flow alone therefore ordered the
    paths almost inversely to their clinical usefulness — «Pre-TAR Era -> Post-TAR Era» beat
    «TAF -> VHB» on an HBV question. Multiplying by the endpoints' cosine similarity to the
    question (already computed in `retrieve_nodes`) restores the paper's premise explicitly."""
    targets = set(nodes)
    best_per_pair: dict[tuple[str, str], _Path] = {}
    for start in nodes:
        for path in _flow_paths(start, targets - {start}, decay, threshold, max_hops):
            path.relevance = (nodes.get(path.nodes[0], 0.0)
                              + nodes.get(path.nodes[-1], 0.0)) / 2
            pair = tuple(sorted((path.nodes[0], path.nodes[-1])))
            current = best_per_pair.get(pair)
            if current is None or path.score > current.score:
                best_per_pair[pair] = path
    return heapq.nlargest(max_paths, best_per_pair.values(), key=lambda p: p.score)


def _path_chunk_ids(paths: list[_Path]) -> list[str]:
    """Chunk ids behind the paths, best-scoring path first. Both the nodes and the EDGES
    contribute: an edge's source chunk is the passage that stated the relation, which is often
    the one that actually answers a multi-hop question."""
    graph = _get_store().graph
    ordered: list[str] = []
    for path in paths:
        for i, node in enumerate(path.nodes):
            ordered.extend(_chunk_ids_of(graph.nodes[node]))
            if i + 1 < len(path.nodes):
                ordered.extend(_chunk_ids_of(graph.edges[node, path.nodes[i + 1]]))
    return ordered


def _describe(item, attrs: dict) -> str:
    """One readable description for a node/edge: the Spanish one when it has been generated,
    else LightRAG's original (English). LightRAG concatenates every extraction of the same
    item with its own separator, so we keep the first and trim it."""
    spanish = _get_store().desc_es.get(_item_key(item))
    if spanish:
        return " ".join(spanish.split())[:DESC_CHARS]
    raw = (attrs.get("description") or "").split(SEP)[0]
    return " ".join(raw.split())[:DESC_CHARS]


def format_paths(paths: list[_Path]) -> str:
    """Render the paths as the non-citable concept map (Spanish: it goes into the generation
    prompt). Ordered by ASCENDING score so the best path sits closest to the question at the
    end of the prompt — the paper's answer to the "lost in the middle" effect, adapted to our
    template (context first, question last).

    The scores themselves are deliberately NOT printed. They rank the paths, but a flow value
    is a topological quantity: shown to a clinical generator (or read off a trace by a doctor)
    a bare «1.70» invites reading it as confidence in the recommendation, which it is not.
    `path_scores` exposes them for tracing instead."""
    if not paths:
        return ""
    graph = _get_store().graph
    lines = []
    for path in sorted(paths, key=lambda p: p.score):
        parts = []
        for i, node in enumerate(path.nodes):
            desc = _describe(node, graph.nodes[node])
            parts.append(f"{node}: {desc}" if desc else node)
            if i + 1 < len(path.nodes):
                nxt = path.nodes[i + 1]
                parts.append(f"  --[{_describe((node, nxt), graph.edges[node, nxt])}]-->")
        lines.append("- " + "\n  ".join(parts))
    return "\n".join(lines)


def path_scores(paths: list[_Path]) -> list[dict]:
    """The ranking behind the concept map, for traces and debugging: which path won, and
    whether it won on graph structure (`flow`) or on closeness to the question (`relevance`).
    Best first — the reverse of the order they appear in the prompt."""
    return [{"path": " -> ".join(p.nodes), "score": round(p.score, 4),
             "flow": round(p.flow, 4), "relevance": round(p.relevance, 4)}
            for p in sorted(paths, key=lambda p: -p.score)]


# ---------------------------------------------------------------------------
# RETRIEVAL  (imported by the registry, the pipeline node and the evaluation)
# ---------------------------------------------------------------------------
def _trace_paths(query: str, paths: list[_Path]) -> None:
    """Record the path ranking in LangSmith as its own step, so a run can be inspected for WHY
    a path was chosen (the prompt only shows the resulting order). Silent no-op without
    tracing configured — it must never affect retrieval."""
    if not paths or not os.environ.get("LANGSMITH_API_KEY"):
        return
    try:
        from langsmith import traceable

        @traceable(name="pathrag_ranking", run_type="retriever")
        def _record(query: str) -> list[dict]:
            return path_scores(paths)

        _record(query)
    except Exception:
        pass



def pathrag_search_with_paths(query: str, top_k: int = 8, node_top_n: int = NODE_TOP_N,
                              max_paths: int = MAX_PATHS, decay: float = DECAY,
                              rewritten_query: str | None = None) -> tuple[list, str]:
    """Full PathRAG retrieval: keywords -> nodes -> pruned paths -> chunks + concept map.

    Returns (payloads, concept_map). The payloads are ordinary citable chunks; the concept map
    is the textual form of the same paths, for the generator to reason over but never quote.
    An empty graph result is not an error — `house_tail`'s hybrid complement still answers."""
    keywords = extract_keywords(query)
    nodes = retrieve_nodes(keywords, top_n=node_top_n)
    paths = retrieve_paths(nodes, max_paths=max_paths, decay=decay) if nodes else []
    _trace_paths(query, paths)
    primary = map_chunk_ids_to_payloads(_path_chunk_ids(paths))[:PRIMARY_CHUNK_CAP]
    return house_tail(query, primary, rewritten_query, top_k=top_k), format_paths(paths)


def pathrag_search(query: str, top_k: int = 8, rewritten_query: str | None = None) -> list:
    """Chunk-only entry point, honouring the retrieval contract shared by every mode (this is
    what the evaluation A/B calls, so all modes are compared on chunks alone)."""
    payloads, _ = pathrag_search_with_paths(query, top_k=top_k, rewritten_query=rewritten_query)
    return payloads


_DESCRIBE_SYS = """Eres un documentalista clínico que describe los conceptos y relaciones extraídos de las guías de VIH (GeSIDA) para un mapa conceptual de apoyo.

Te doy un FRAGMENTO de la guía y una lista numerada de ELEMENTOS extraídos de él: conceptos (un término) y relaciones (dos términos unidos por «↔»).

Para cada elemento escribe UNA frase en ESPAÑOL, de 25 palabras como máximo, que diga lo que el fragmento afirma sobre él:
- Para un CONCEPTO: qué es y qué papel clínico tiene según el fragmento.
- Para una RELACIÓN: qué vínculo establece el fragmento entre ambos términos (indicación, contraindicación, ajuste de dosis, interacción, alternativa…).
- Usa la terminología del fragmento y conserva el dato clínico concreto (fármaco, situación, grado de recomendación) cuando lo haya.
- NO inventes nada que el fragmento no diga. Si el fragmento apenas habla del elemento, descríbelo de forma escueta y general.
- No traduzcas los nombres propios ni las siglas.

Devuelve descriptions: una lista con EXACTAMENTE una entrada por elemento, en el MISMO orden (campo index = el número del elemento, campo text = la frase)."""


def _describe_schema() -> dict:
    return {
        "name": "descriptions",
        "strict": True,
        "schema": {
            "type": "object",
            "additionalProperties": False,
            "required": ["descriptions"],
            "properties": {
                "descriptions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "required": ["index", "text"],
                        "properties": {"index": {"type": "integer"},
                                       "text": {"type": "string"}},
                    },
                }
            },
        },
    }


def _items_by_chunk() -> dict[str, list]:
    """Group every node and edge under the chunks it was extracted from, so each LLM call can
    describe a whole chunk's items while reading that chunk once."""
    graph = _get_store().graph
    by_chunk: dict[str, list] = {}
    for node, attrs in graph.nodes(data=True):
        for cid in _chunk_ids_of(attrs):
            by_chunk.setdefault(cid, []).append(node)
    for u, v, attrs in graph.edges(data=True):
        for cid in _chunk_ids_of(attrs):
            by_chunk.setdefault(cid, []).append((u, v))
    return by_chunk


async def _describe_chunk(cid: str, text: str, items: list,
                          semaphore) -> dict:
    """Describe one chunk's items in Spanish. A failure yields nothing for that chunk: those
    items keep LightRAG's English description (`_describe` falls back)."""
    listing = "\n".join(
        f"{i}. {it if isinstance(it, str) else f'{it[0]} ↔ {it[1]}'}"
        for i, it in enumerate(items)
    )
    async with semaphore:
        try:
            response = await asyncio.to_thread(
                client.chat.completions.create,
                model=REPHRASE_MODEL,
                temperature=0,
                messages=[{"role": "system", "content": _DESCRIBE_SYS},
                          {"role": "user",
                           "content": f"FRAGMENTO:\n{text}\n\nELEMENTOS:\n{listing}"}],
                response_format={"type": "json_schema", "json_schema": _describe_schema()},
            )
            data = json.loads(response.choices[0].message.content)
            out = {}
            for d in data["descriptions"]:
                i = d["index"]
                if 0 <= i < len(items) and d["text"].strip():
                    out[_item_key(items[i])] = d["text"].strip()
        except Exception as exc:
            print(f"  ! {cid}: {type(exc).__name__}")
            out = {}
    return {"chunk_id": cid, "descriptions": out}


async def _generate_descriptions_es() -> None:
    """Regenerate every node/edge description in Spanish from its source chunk. Resumable at
    the chunk level (append-only JSONL), like the other index builds."""
    from ._common import load_chunks

    chunks = {c["chunk_id"]: c for c in load_chunks()}
    by_chunk = _items_by_chunk()
    done = set()
    if os.path.isfile(DESCRIPTIONS_ES):
        with open(DESCRIPTIONS_ES, encoding="utf-8") as fh:
            done = {json.loads(l)["chunk_id"] for l in fh if l.strip()}
    todo = [c for c in by_chunk if c in chunks and c not in done]
    total_items = sum(len(by_chunk[c]) for c in todo)
    print(f"Spanish descriptions: {len(done)} chunks done, {len(todo)} to go "
          f"({total_items} items).")
    if not todo:
        return

    semaphore = asyncio.Semaphore(OPENIE_CONCURRENCY)

    async def describe_all(cid: str) -> dict:
        """One chunk, in batches — the results are written as a single resumable record."""
        items = by_chunk[cid]
        batches = [items[i:i + DESCRIBE_BATCH] for i in range(0, len(items), DESCRIBE_BATCH)]
        parts = await asyncio.gather(
            *[_describe_chunk(cid, chunks[cid]["text"], b, semaphore) for b in batches])
        merged: dict[str, str] = {}
        for p in parts:
            merged.update(p["descriptions"])
        return {"chunk_id": cid, "descriptions": merged}

    tasks = [asyncio.create_task(describe_all(c)) for c in todo]
    described = 0
    with open(DESCRIPTIONS_ES, "a", encoding="utf-8") as fh:
        for i, task in enumerate(asyncio.as_completed(tasks), 1):
            record = await task
            described += len(record["descriptions"])
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")
            fh.flush()
            if i % 25 == 0 or i == len(todo):
                print(f"  {i}/{len(todo)} chunks · {described}/{total_items} items described")
    print(f"Written to {DESCRIPTIONS_ES}")


if __name__ == "__main__":
    if "--describe-es" in sys.argv:
        asyncio.run(_generate_descriptions_es())
        raise SystemExit(0)

    # Smoke: store integrity + the graph stages of a demo query. Only the final house_tail
    # needs Qdrant, so everything above it can be checked offline.
    store = _get_store()
    print(f"Store: {store.graph.number_of_nodes()} nodes, {store.graph.number_of_edges()} "
          f"edges, embeddings {store.node_emb.shape}, "
          f"{len(store.lr_to_chunk)} LightRAG chunks mapped to our payloads.")

    demo = ("En un paciente con coinfección por VHB que inicia TAR, "
            "¿qué fármacos debe incluir el régimen?")
    keywords = extract_keywords(demo)
    print(f"\nQuery: {demo}\nKeywords: {keywords}")
    nodes = retrieve_nodes(keywords)
    print(f"Nodes ({len(nodes)}): {list(nodes)[:10]}")
    paths = retrieve_paths(nodes)
    print(f"Paths ({len(paths)}), best first  [score = flow x relevance]:")
    for p in path_scores(paths)[:8]:
        print(f"  {p['score']:.4f} = {p['flow']:.3f} x {p['relevance']:.3f}   {p['path']}")
    selected = map_chunk_ids_to_payloads(_path_chunk_ids(paths))
    payloads = selected[:PRIMARY_CHUNK_CAP]
    print(f"\nChunks selected by the paths: {len(selected)} -> keeping {len(payloads)}")
    for p in payloads:
        print(f"  {p['chunk_id']} | {p['source_file']} | {(p.get('heading') or '')[:60]}")
    print("\nConcept map (ascending score, non-citable — scores not shown to the LLM):")
    print(format_paths(paths)[:1200])
